### ISSUE TITLE
Melee jobs remain at range

### ISSUE THREAD

**Issue by StarkITA** [FFXIV-CombatReborn/BossmodReborn#227]
I am using BM in combination with AD. I have noticed that often, particularly on bosses, melee jobs remain at range and do not directly engage with melee skills.

These are my settings through AD:

![image](https://github.com/user-attachments/assets/65a1e023-ff71-4c11-9644-a4af7eaf9781)

Is this applicable to BMR? I thought to open the issue here, because it does seem mostly related to BMR and I have noticed this behaviour even without AD.

Thanks!

EDIT: I have been monitoring it for a while, and it seems to behave, now, and I couldn't reproduce it anymore. I have updated it after I created the issue, maybe it solved itself?

**Comment by leroidubid** [comment]
What's AD ?
