### ISSUE TITLE
Custom Queueing Pet Glamour Error

### ISSUE THREAD

**Issue by fang-anon** [FFXIV-CombatReborn/BossmodReborn#243]
Turning on 'Use custom queueing for manually pressed actions' disables Pet Glamours.  It will only give you Eos, blue Carbuncle, and the Egis as their default.  The SMN's Pet Size settings work fine.
(Not able to test if this is a user issue or universal visual issue because I have no friends.)

**Comment by CarnifexOptimus** [comment]
I have no idea about how this feature works, you will probably have to ask the maker of vbm about it.

**Comment by CarnifexOptimus** [comment]
I believe this is fixed in the new versions, give it a try
