### ISSUE TITLE
Tower of Babil - Anima

### ISSUE THREAD

**Issue by Buckfutt** [FFXIV-CombatReborn/BossmodReborn#245]
During the Final Fight against Anima, the 2nd phase of the fight, 2nd mechanic (Chasing Spikes). AI does not run far enough away to avoid getting hit multiple times, and dying, from the mechanic.

**Comment by CarnifexOptimus** [comment]
I think the problem lies with the fact that when a circle AOE spawns pixel perfectly on the AI controlled character all paths to safety have the same distance, so it can't decide where to go.

**Comment by CarnifexOptimus** [comment]
Can you test if the new update reduces the problem

**Comment by Buckfutt** [comment]
i'll give it a test tonight, thanks!

**Comment by Buckfutt** [comment]
Works perfectly now!

**Comment by CarnifexOptimus** [comment]
grear
