### ISSUE TITLE
Mount Rokkon Modules

### ISSUE THREAD

**Issue by VeraNala** [FFXIV-CombatReborn/BossmodReborn#246]
To accompany the logs uploaded:

### V021 - Module missing following mechanics -> 
Gales = Windblossom Whorl - Incorrect AoE Size
Rain = Sludge - Not represented
Tatami Trap + Tatami-Gaeshi = Half-room wide AoE
Levinblossom Lance = Rotating Line AoE from center origin is missing the last AoE (# of AoE's mismatched)

### V022 - Module missing following mechanics -> 
Spearman's Orders = (Gradual Room-wide charge like Zeromus Bio)
Boundless Azure = Movement prone to error
Boundless Auspice = Movement prone to error
Yama-Kagura
Spiritflame = Dodging not adequate/prioritized

### V023 - Module missing following mechanics -> 
Sulphuric Stone+Morphic Memory = incorrect AoE size (AoE turns into Donut with too large of an inner radius)
RousingReincanation + RodentialRebirth + Dramatic Burst Towers = Not considered safezones. (Last tower extremely dangerous as it is paired with a player-origin, targeted AoE)
East-West *BallofLevin/Shock* = AoEs are represented as larger than actual. 
Four corner BallofLevin/Shock = AoEs are not represented at all (should be 3 large AoEs, 1 small one signifying safespot)
Worldly Pursuit = first AoE is not represented

### V024 - Module missing following mechanics -> 
Noble Pursuit = Forward Charge is represented but the rings/sideAoEs are not. 
Haunting Thralls = Not properly avoided, leading to wipes. (should be treated as a following AoE)

### V025 - Module missing following mechanics -> 
Some Quakes/Scaling AoEs (Bedrock Uplift?) = Not accurately represented, 
Clearing Smoke (Knockback) = Not prioritized, leading to walling.
Into the Fire = Represented too late, leading to getting hit multiple times throughout the fight, although the smoke telegraph should signal where the boss will reappear

### Mount Rokkon | E1 | Logprovided
B2: Module missing following mechanics -> Spearman's Orders, Boundless Azure Movement prone to error
### Mount Rokkon | E2 | Logprovided
B2: No Module -> Spearman's Orders, Boundless Auspice Movement prone to error
### Mount Rokkon | E3 | Logprovided
B2: Module missing following mechanics -> Spearman's Orders, Yama-Kagura, Boundless Azure Movement prone to error
### Mount Rokkon | E4 | Logprovided
B1: Gales = Windblossom Whorl - Incorrect AoE Size , Rain = Sludge
B2: Module missing following mechanics -> Spearman's Orders, Boundless Auspice Movement prone to Error, Spiritflame dodging not adequate/prioritized
### Mount Rokkon | E5 | Logprovided
B3: Module missing following mechanics -> Sulphuric Stone+Morphic Memory incorrect AoE size (AoE turns into Donut with too large of an inner radius), RousingReincanation + RodentialRebirth + Dramatic Burst Towers Not considered safezones. (Last tower extremely dangerous as it is paired with a player-origin, targeted AoE)
### Mount Rokkon | E6 | Logprovided
B3: Module missing following mechanics -> East-West *BallofLevin/Shock* AoEs are represented as larger than actual. Four corner BallofLevin/Shock AoEs are not represented at all (should be 3 large AoEs, 1 small one signifying safespot)RousingReincanation + RodentialRebirth + Dramatic Burst Towers Not considered safezones. (Last tower extremely dangerous as it is paired with a player-origin, targeted AoE)
### Mount Rokkon | E7 | Logprovided
B1: Module missing following mechanics -> Tatami Trap + Tatami-Gaeshi (Half-room wide AoE), Levinblossom Lance (Rotating Line AoE from center origin) is missing the last AoE (# of AoE's mismatched)
B3: Module missing following mechanics -> Worldly Pursuit first AoE is not represented
### Mount Rokkon | E8 | Logprovided
B4: Module missing following mechanics -> Noble Pursuit - Forward Charge is represented but the rings/sideAoEs are not.
### Mount Rokkon | E9 | 
B1: Module missing following mechanics -> Sludges not represented
B4: Module missing following mechanics -> Noble Pursuit - Forward Charge is represented but the rings/sideAoEs are not.
### Mount Rokkon | E10 | Logprovided
B1: Module missing following mechanics -> Sludges not represented
B4: Module missing following mechanics -> Noble Pursuit - Forward Charge is represented but the rings/sideAoEs are not.
### Mount Rokkon | E11 | Logprovided
B1: Module missing following mechanics -> Sludges not represented
B4: Module missing following mechanics -> Noble Pursuit - Forward Charge is represented but the rings/sideAoEs are not. Haunting Thralls are not properly avoided, leading to wipes. (following AoE)
### Mount Rokkon | E12 | Logprovided
B5: Module missing following mechanics -> Some Quakes/Scaling AoEs (Bedrock Uplift?) are not accurately represented, Knockback (Clearing Smoke) is not prioritized, Into the Fire represented too late, leading to getting hit multiple times throughout the fight.

**Comment by CarnifexOptimus** [comment]
Mount Rokkon rework is complete for now, please open a new issue if you are going to test the updated modules and find issues.
