### ISSUE TITLE
Aetherochemical Research Facility - Harmarchis - Tank job

### ISSUE THREAD

**Issue by davlar12** [FFXIV-CombatReborn/BossmodReborn#256]
So, running with trust as a tank (assuming this matters for the purpose of trust AI), the second boss of the dungeon has this ability that deals near fatal damage if the target doesn't have a single extra party member in a circle with them. It's then followed by party-wide damage.

The mod logic seems to keep the player character inside the aoe circle and proceeds to murder the two trusts that try to pair up for the mechanic. Seeing as I was running as warrior it manages to survive barely the encounter.

**Comment by CarnifexOptimus** [comment]
I don't really understand the problem. Do you have a video or some screenshots?

**Comment by CarnifexOptimus** [comment]
Why do you close the issue instead of providing something to help me visualize the problem?

**Comment by VeraNala** [comment]
This issue was crossposted here, with a video: https://github.com/ffxivcode/AutoDuty/issues/158 if it helps any.

**Comment by CarnifexOptimus** [comment]
> This issue was crossposted here, with a video: [ffxivcode/AutoDuty#158](https://github.com/ffxivcode/AutoDuty/issues/158) if it helps any.

so the solution would be to run out if there are already 2 targets inside (assuming you are not the target?)

**Comment by VeraNala** [comment]
Yes, the mechanic is *solved* when exactly two people are in the marker, and no more.
Whoever is targeted by the aoe is rooted in place however, so they will always be part of the stack either way.
It might honestly just be easiest to treat it as a marker to avoid outright and just let npcs handle it but I'm sure you'd prefer a *correct* solution.

**Comment by CarnifexOptimus** [comment]
Can you test if the new update fixes the problem? AI should now avoid stack markers with enough or too many players inside
