### ISSUE TITLE
[Bug Report] Ghost Mechanics

### ISSUE THREAD

**Issue by Ecselsior** [FFXIV-CombatReborn/BossmodReborn#257]
Hi, I'm having a problem that I'm calling 'ghost mechanics', this is when Bossmod displays a mechanic that never appears, which causes a wipe, because your character is trying to avoid a mechanic that simply isn't there.

This bug seems to appear after you first die during a duty (unconfirmed) or when the plugin is updated during a duty(unconfirmed), and persists until ```/xlrestart```(confirmed) or ```"Reset plugin and data"```(unconfirmed). Simply leaving and re-joining the duty does not fix it.(confirmed)

I have linked a video, which I hope will give some insight. It is in Alexandria, but I don't think this problem is unique to this duty. As you can see, BMR reports a frontal cone from the boss which never comes (ghost). You can see as I manually try to walk out of the real AOE, but the AI pulls me right back in and I take a vuln stack:
https://www.file.io/2A1N/download/tRlUCBTTj1TK

When this issue occurs with A*toDuty enabled, it results in a loop of running to the boss then dying. If there is no clear way to resolve this, is it possible to implement a command that resets the state of the plugin, but not the config? (something like ```/bmr resetstate``` which I could use whenever I detect a death)

I have attached a horribly compressed version also that meets the 10mb GitHub limit. If there is another file sharing site that doesn't require an account, I would be happy to reupload it there.
https://github.com/user-attachments/assets/8e1e0413-176a-4c0d-8ad7-13caf07dfbf8

**Comment by CarnifexOptimus** [comment]
I can't reproduce this. I would test if it is caused by another plugin. Modules reset if the whole party wipes or if the boss is no longer in the object table. Updating during an active boss module will just cause less things being shown due to lack of data and not more.

As seen in your video the radar only appears when the boss is being loaded. This means it was correctly unloaded before or the radar would have stayed up the whole time.

**Comment by Ecselsior** [comment]
Hello again, it is possible to be a conflict since I have many plugins enabled though I am not sure what this conflict would be exactly. Here is my full plugin list (note that it contains plugins I have disabled): https://pastebin.com/xsZP0gjf
Also, here is my redacted chatlog, and as you can see this happened on the 7th concurrent run of Alexandria, so this might be difficult to reproduce. (I like to do 9 so i can reach the weekly tomestone cap for each alt): https://pastebin.com/vq2VDY3R
As for additional information I can give. the video was taken on the release branch of Dalamund, but I encountered this problem previously on the testing branch as well.

I will try to reproduce this again and see if there is anything in ```/xllog```.

**Comment by CarnifexOptimus** [comment]
I would suggest deleting xivlauncher including all plugins and configs and then reinstalling Xivlauncher starting with bossmod and then see after which plugin the bug comes back (if at all).
Since you are the first person of almost 5000 users to report this, I don't think that it is caused by BMR.
