### ISSUE TITLE
Radar Position Change On Resolution/Window Size Change

### ISSUE THREAD

**Issue by larryboxaplenty8** [FFXIV-CombatReborn/BossmodReborn#279]
Can you add an option to keep the position of the BossMod radar on the same place of the screen despite resolution changes / window re-size? It's annoying to be opening windows to check something and the radar moves back to the bottom middle of the screen.  I am not moving it manually - the lock position option is checked when it happens.

**Comment by CarnifexOptimus** [comment]
saving window positions is entirely handled by dalamud, so you would probably need to ask on the dalamud discord to save window positions for resolution changes

**Comment by larryboxaplenty8** [comment]
> saving window positions is entirely handled by dalamud, so you would probably need to ask on the dalamud discord to save

I'm saying if the Window is say in split screen mode so half the game is the screen and half is something else - when I return the game to being maximized, the radar is moved from where I had it before - even when the lock position option is checked.  Can you add a feature to stop this from happening so it always stays in the same position even if that would mean not seeing it?  I don't need to see it while split screen - I just don't want to have to keep moving it back all the time.

**Comment by CarnifexOptimus** [comment]
The lock position setting just make it so you cannot accidently move the window + makes you able to clickthrough it. The window position itself is handled by Dalamud.
