### ISSUE TITLE
Worqor Zormor - second boss

### ISSUE THREAD

**Issue by ayo-bruh** [FFXIV-CombatReborn/BossmodReborn#286]
2 issues with Kahderyor (giant bird boss) when running w/ trusts:

1. Char can try to adjust mult times for trust NPCS (issue when they both caster+healer) during spread marker mech (Earthen Shot), will try to find safespot but cant in time, sometimes wiping to this + ground aoe. Will see mech twice, increasing chance of bad pattern
2. Doe not always target own Crystalline Debris from Seed Crystals, leading to wipe when Crystallized from debuff

in conjunction with current RSR and AD if matters. ilvl 663 SAM
current version, 7.2.0.79

**Comment by CarnifexOptimus** [comment]
at least the 2nd issue is because RSR needs to be set to auto target small or low HP

**Comment by ayo-bruh** [comment]
^changed to that, no issues now, thx

char will still try to late adjust for npc but seems survivable now on melee (maiming). and prange too

**Comment by CarnifexOptimus** [comment]
if you find a way to predict which safespot will have a free spot let me know. i think it is different depending on which NPCs you play with

**Comment by SonicZeHedgehog** [comment]
> if you find a way to predict which safespot will have a free spot let me know. i think it is different depending on which NPCs you play with

I'll admit I haven't delved too much into the code, but is there a way to delay the movement on a spread? Typically the AI moves your character immediately to a safe spot when SpreadFromCastTargets is called, then a few seconds later the trusts try to move to a safe spot. If that safe spot happens to have your character, then your character tries to moves. I'm thinking if the spread is delayed slightly then maybe that'll give your character enough time to move to another safe spot when it sees the trusts go to another spot. Also maybe this delay should only be used when Crystalline Storm or/and Earthen Shot is active, so all spreads in the fight aren't affected. There could be a better way to do this, but this is what I came up with at the moment. I hope all of this makes sense.

**Comment by CarnifexOptimus** [comment]
Not sure if delaying would help, the NPCs move pretty late themselves which causes this problem in first place. The cast time is 6s, but its quite possible for 5s to already have passed before the NPCs arrive at their safespot

**Comment by CarnifexOptimus** [comment]
This should be fixed in version 7.2.0.97, at least I don't get killed by Krile in my tests anymore.
