### ISSUE TITLE
Tower of Zot

### ISSUE THREAD

**Issue by Purgeitonic** [FFXIV-CombatReborn/BossmodReborn#293]
Not sure if this is supposed to be here but.. Tower of Zot AI isn't running as intended.
The Boss 1 and 2 have no AOE mapping as well.

**Comment by CarnifexOptimus** [comment]
Did you disable modules with contributed maturity level? The tower of zot modules should work mostly fine

**Comment by CarnifexOptimus** [comment]
Closing since no further communication from OP
