### ISSUE TITLE
Hydaelyn Ex breaks halfway through

### ISSUE THREAD

**Issue by OldYharn** [FFXIV-CombatReborn/BossmodReborn#299]
The Hydaelyn EX window breaks at the crystal phase and never recovers. It shows the cross aoe pattern on the window for the remainder of the Trial.

**Comment by CarnifexOptimus** [comment]
do you have a replay where this happens?
My guess is that it breaks because damage in unsync is too high so some mechanics get skipped. Since the module is old the creator of it probably didn't futre proof it

**Comment by CarnifexOptimus** [comment]
unsynced hydealyn ex should be fixed in 7.2.0.154
