### ISSUE TITLE
Nald'Thal window does not display any information

### ISSUE THREAD

**Issue by OldYharn** [FFXIV-CombatReborn/BossmodReborn#300]
The window for Nald'Thal in Aglaia does not show any information throughout the entire fight.

**Comment by CarnifexOptimus** [comment]
did you join the fight late eg waiting until you get teleported in? fights with timelines break if you aren't there from the beginning. same applies if you update the plugin during the fight

**Comment by OldYharn** [comment]
> did you join the fight late eg waiting until you get teleported in? fights with timelines break if you aren't there from the beginning. same applies if you update the plugin during the fight

Ah yep! That'd do it. I was watching the cutscene and they pulled early. Thanks!

**Comment by CarnifexOptimus** [comment]
That is unfortunate, at least it will work next time you get it in roulette
