### ISSUE TITLE
[bug] worqor zormor first boss "Frozen Swirl" cast not showing in module.

### ISSUE THREAD

**Issue by Dedoooo** [FFXIV-CombatReborn/BossmodReborn#356]
i saw the ai stand between two frozen swirl casts, this doesn't happen all the time so there must be a cast missing. it kept dying repeatedly to them for 6 pulls, not showing aoes on the module. managed to avoid them on the 7th but they were a different cast.

**Comment by CarnifexOptimus** [comment]
do you have a replay of this? never seen this happen

**Comment by CarnifexOptimus** [comment]
You can use the bossmod replay feature, no need for ARR
