### ISSUE TITLE
HighHeat

### ISSUE THREAD

**Issue by yuwuhuolongyi** [FFXIV-CombatReborn/BossmodReborn#413]
Hello, I found a problem. When the character is in High Heat state, no matter how long the fever is left, the character's movement and casting will be disabled, which will put the player in a very embarrassing situation in the A22 copy (standing for up to 15 seconds). Is it possible to add an adjustable option or switch for the relevant function? (The above text is from Google Translate, I hope it will not offend you.)

**Comment by CarnifexOptimus** [comment]
i don't know, i think too much information got lost in translation
is this like a mechanist problem or what is this about

**Comment by CarnifexOptimus** [comment]
if your english is bad you could send me a video or screenshot on discord showing the problem, maybe it helps to understand

**Comment by yuwuhuolongyi** [comment]
> if your english is bad you could send me a video or screenshot on discord showing the problem, maybe it helps to understand

Ok I will send it to you in the near future

**Comment by CarnifexOptimus** [comment]
any update on this?
