### ISSUE TITLE
could't install successfully

### ISSUE THREAD

**Issue by cHildish0526** [FFXIV-CombatReborn/BossmodReborn#414]
![QQ截图20241020223704](https://github.com/user-attachments/assets/49ffa8dd-2770-44de-82eb-c5ba3b210f0a)
![QQ截图20241020230312](https://github.com/user-attachments/assets/3ea3a260-a105-4d60-b715-dbf435ac3d8c)
I have tried to install the profile both ways,download the latest release and load it on dalamud,all failed

**Comment by gzuuuul** [comment]
Maybe try this?
https://github.com/44451516-ff14/BossmodRebornCN
