### ISSUE TITLE
Autorotation is enabled as long as AI is enabled. (as of 7.2.0.209)

### ISSUE THREAD

**Issue by Eclipsum** [FFXIV-CombatReborn/BossmodReborn#478]
Autorotation is enabled as long as AI is enabled. (as of 7.2.0.209) and yes, I have updated and restarted multiple times to the newest release. 

Manually disabling it in autorotation works, but gets instantly re-enabled, same case for slash commands.
Tested on multiple jobs.

**Comment by CarnifexOptimus** [comment]
![Untitled](https://github.com/user-attachments/assets/3cafcda8-d277-49e4-a4bf-4967793747a4)
is your AI autorotation preset empty? if not that autorotation will be enabled every time you activate AI. its also getting saved inside the config file, so restarting the plugin or game will not remove it.
