### ISSUE TITLE
after update no longer transparent background

### ISSUE THREAD

**Issue by karmaspcs** [FFXIV-CombatReborn/BossmodReborn#511]
after the last update i have the problem that the radar dosent work on the corners anymore. only in somewhere in the middle of my monitor i get the transparent background again

**Comment by karmaspcs** [comment]
multi monitor setup

**Comment by CarnifexOptimus** [comment]
it is rolled back in 7.2.0.238, it seems like the 3 year old version of imgui Dalamud is using doesn't like the changes
